# Generated by Django 3.2.5 on 2022-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='brands',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
